### ISSUE TITLE
Html Webpack Plugin: <pre>   Error: Parse Error: .... on if-shorthand inside html-tag

### ISSUE THREAD

**Issue by hubionmac** [RomainMazB/octobercms-tailwindcss-boilerplate#23] opened 2021-03-06 12:32 UTC
Is just wanted to modify a translation selection when I ran into a parse error in wepack.
I a note sure on which stage this error occures and how to fix it instead of tweaking the twig-code
`{% component 'localePicker' %}` is expanded to the original code:
```
{{ form_open() }}
    <select name="locale" data-request="onSwitchLocale" class="form-control">
        {% for code, name in locales %}
            <option value="{{ code }}" {{ code == activeLocale ? 'selected' }}>{{ name }}</option>
        {% endfor %}
    </select>
{{ form_close() }}
```

where 
`<option value="{{ code }}" `**`{{ code == activeLocale ? 'selected' }}`**>`{{ name }}</option>`

causes a parse error
the only work around for me was to write
```
{{ form_open() }}
    <select name="locale" data-request="onSwitchLocale" class="form-control">
        {% for code, name in locales %}
            {% set isSelected = (code == activeLocale ? 'selected':'') %}
            <option value="{{ code }}" {{ isSelected }}>{{ name }}</option>
        {% endfor %}
    </select>
{{ form_close() }}
```

to make this somehow work, since I have no clue how to change webpack.config.js to fix this ...

**Comment by RomainMazB** [comment] 2021-03-06 12:59
The problem is the ternary operator, which could not be parsed by the html minifier.

Described with workaround in #18 to disable the html minifier

**Comment by RomainMazB** [comment] 2021-06-24 20:20
Fixed by https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/commit/e06cc92edea0fccdb3e09957adc1333b466b6b92

**Closed as completed by RomainMazB** 2021-06-24 20:20 UTC
